# Generated by Django 4.2.21 on 2025-05-13 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_and_owners_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bird',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.DeleteModel(
            name='ExoticAnimal',
        ),
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='number_of_pets',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
