# Generated by Django 4.2.21 on 2025-05-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_and_owners_app', '0002_delete_bird_delete_cat_delete_dog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
