# Generated by Django 4.2.21 on 2025-05-13 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_and_owners_app', '0003_alter_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='number_of_pets',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
