# Generated by Django 4.2.21 on 2025-05-13 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_and_owners_app', '0004_alter_owner_age_alter_owner_number_of_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(default='Unknown', verbose_name=255)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('vaccinated', models.BooleanField(default='Unknown')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
