# Generated by Django 4.2.21 on 2025-05-13 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_and_owners_app', '0005_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=255)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('vaccinated', models.BooleanField()),
                ('description', models.TextField(blank=True, default='No description')),
                ('species', models.CharField()),
            ],
        ),
    ]
