# Generated by Django 4.2.21 on 2025-05-13 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_and_owners_app', '0007_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExoticAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_of_origin', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('type_of_animal', models.CharField(max_length=100)),
                ('vaccinated', models.BooleanField(default='Unknown')),
            ],
        ),
    ]
