# Generated by Django 4.2.21 on 2025-05-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store_app', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_init', models.CharField(blank=True, max_length=1)),
                ('age', models.IntegerField(default=18)),
            ],
        ),
    ]
