# Generated by Django 4.2.21 on 2025-05-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store_app', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('appt_num', models.IntegerField()),
            ],
        ),
    ]
