# Generated by Django 4.2.21 on 2025-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store_app', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_employees', models.IntegerField()),
                ('rating', models.FloatField()),
                ('owner', models.IntegerField()),
            ],
        ),
    ]
